### ISSUE TITLE
Feature Request: Functionality to migrate from streamdeck-linux-gui to StreamController

### ISSUE THREAD

**Issue by LukeShirnia** [StreamController/StreamController#32]
Hey! Amazing work on this, I really like it and I'm looking to move over from streamdeck-linux-gui to StreamController.

I'm not sure if here is the best place to request it or if you'd want it on the main repo but I thought I'd start here. 

I understand you might be in contact/communication with the team that does streamdeck-linux-gui (I saw this comment which directed me to your repo: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/pull/198#issuecomment-2050210228), so I don't know what the plans are but I think it would be amazing to have a migration script of some sort to port over from my previous streamdeck-linux-gui config to StreamController.

Everything I've got running on the streamdeck-linux-gui is a bash/python script, so this OSPlugin is probably the best place for the request. 

I've got about 20 pages worth of stuff in my previous config and it's a little daunting to move it all over. I think you'd open up your application to quite a big audience if it were super simple to move over the most of the config. I appreciate it can't account for everything but if the bulk of the work could be done quickly, I'm sure a large collection of people would be greatly appreciative. 

Thanks!

**Comment by coolapso** [comment]
I'd say the best place for this issue is in the main streamcontroller repository [here](https://github.com/StreamController/StreamController)

**Comment by Core447** [comment]
I will look into this

**Comment by Core447** [comment]
You can try the experimental importer in the `page-import` branch

**Comment by v4u6h4n** [comment]
@Core447 

Hey there :-)

Just heard about this project through the streamdeck-gui github. Looks fantastic.

I have 4 streamdecks with 200 pages each (do a lot of streaming with my GF), so thanks for implementing the import feature. I just tried it, and it successfully imported the pages, button positions, colours, command actions and page switch actions.

However it didn't import any values for the page switch commands (the action was there, but empty), and no existing images/icons. I don't really care about the icons (drag on drop is easy), but I'm wondering what the chances are of getting the switch values to be imported correctly, as that will certainly save quite a lot of time.

**Comment by Core447** [comment]
Thanks for your feedback.

I also noticed some problems with the page switch action during my testing. I'll check everything and add support for the "Write Text" action as well.

**Comment by Core447** [comment]
I changed some things. Could you please try again?

**Comment by v4u6h4n** [comment]
@Core447 

Happy to help :-)

I just gave it another shot, and unfortunately I haven't been able to get it working.

It may be an unrelated issue, but it seems to be only importing one of the streamdecks from the streamdeck-gui json file, specifically the last one in the file, and applies that single deck to all of my decks when importing. Additionally, I tested a single deck import from the json (modified the original json to include only one deck), but it didn't make a difference. I disconnected all but one of my decks and tried again, just in case that was effecting anything, but still nothing.

On the plus side, the images did load this time, it was just unsupported .svg files not loading last time, so thats good.

Don't know if it'll be much help, but here's the log:

[logs.log](https://github.com/StreamController/StreamController/files/14969536/logs.log)

**Comment by Core447** [comment]
@v4u6h4n 
What's weird is that if I add more decks to the export, it goes through all of them. I added a couple more logs to the script to be able to debug it better. Would you mind pulling the latest changes and capturing the logs?

**Comment by v4u6h4n** [comment]
@Core447 

Okay I just gave it another shot, still not working. It's odd, because I can see, at least what I think is, pages in the actual page file, but they are just not visible, or working when I press the associated buttons, or when I select the page action in the gui, the page and streamdeck drop downs are just empty. If I click on a few buttons, eventually the left side panel contents is replaced with `Error`.

Oh, and probably unrelated, but the 4 streamdecks are listed as `StreamDeck Mini` and then 3x `Streamdeck Mini 2`, instead of `Streamdeck Mini 3` and `Streamdeck Mini 4`.

[logs.log](https://github.com/StreamController/StreamController/files/14974275/logs.log)

[ui_1.json](https://github.com/StreamController/StreamController/files/14974270/ui_1.json)

EDIT: just noticed the `"deck_number": null` in the `ui_1.json` *facepalm* maybe it's just not managing the streamdeck number correctly?

**Comment by Core447** [comment]
> ui_1.json

This pages works for me:
![image](https://github.com/StreamController/StreamController/assets/100139110/c3053197-0c4b-4ad8-bde4-e2539ccb1837)

`"deck_number": null` is normal and just means that it should change the page on whatever deck the page is loaded on.

I haven't found anything problematic in the logs so far, but I'm going to delve into them a bit more later on.

Edit: Make sure to switch to the `main` branch for further testing, because I merged the `page-import` branch.

**Comment by Core447** [comment]
> Oh, and probably unrelated, but the 4 streamdecks are listed as `StreamDeck Mini` and then 3x `Streamdeck Mini 2`, instead of `Streamdeck Mini 3` and `Streamdeck Mini 4`.

This should be fixed with c1655b6f9e4b1efc9b9ef7657ccab36dc3874132

**Comment by v4u6h4n** [comment]
Okay, I've switched to the main branch, yeah seems [c1655b6](https://github.com/StreamController/StreamController/commit/c1655b6f9e4b1efc9b9ef7657ccab36dc3874132) was unrelated, but it's fixed :-)

EDIT: Looking at the logging whilst I mess around with the GUI, I can see that the error in the side panel is not being logged.

https://github.com/StreamController/StreamController/assets/156973064/461e5ed2-b9bd-46ff-a48c-6f5e23c0537d

**Comment by Core447** [comment]
I'll check under which conditions this error appears.

**Comment by Core447** [comment]
> It may be an unrelated issue, but it seems to be only importing one of the streamdecks from the streamdeck-gui json file, specifically the last one in the file, and applies that single deck to all of my decks when importing

StreamController works a bit differently with pages/profiles. The pages are not bound to a deck, but are available for all decks. You can use the page manager (folder button next to the page drop down) to control which page should be loaded on which deck when the application starts.

**Comment by v4u6h4n** [comment]
> StreamController works a bit differently with pages/profiles. The pages are not bound to a deck, but are available for all decks. You can use the page manager (folder button next to the page drop down) to control which page should be loaded on which deck when the application starts.

Ah okay, love it :-)

Also, if it helps, I can send you my streamdeck-gui export file.

**Comment by Core447** [comment]
> Also, if it helps, I can send you my streamdeck-gui export file.

This would be nice! Please make sure to remove everything personal

**Comment by v4u6h4n** [comment]
Don't think there was anything personal on there, but stripped all the commands and images out just in case; think the pages and page switching actions are probably what's most relevant anyway.

[2024-04-16.json](https://github.com/StreamController/StreamController/files/14988143/2024-04-16.json)

**Comment by Core447** [comment]
@v4u6h4n 
> [2024-04-16.json](https://github.com/StreamController/StreamController/files/14988143/2024-04-16.json)

Fixed some things and now this export can be imported flawlessly. Seams like the app had a hard time handling all the refreshes because of the huge amount of pages. Could you please try again using the newest state of `main`? Thanks

**Comment by v4u6h4n** [comment]
Yeah there's a lot of pages! :-) Although there will be a lot less once I've migrated; it's mostly duplication.

I tried it again, this time I'm using the same JSON that I provided to you, just so we can rule out other variables. I'm still having some issues. Only some of the background colours are loading. I can see them in the button settings panel, but they are not being displayed, and the page switching still doesn't seem to be working. I can see page switching and colours in the page file though.

https://github.com/StreamController/StreamController/assets/156973064/d4d7a4f5-3f8c-47ac-a46d-5a4d01da8cae

[ui_1.json](https://github.com/StreamController/StreamController/files/15004059/ui_1.json)

[logs.log](https://github.com/StreamController/StreamController/files/15004058/logs.log)

**Comment by Core447** [comment]
Looks like I forgot to update some references. I'll come back to you if I fixed it

**Comment by Core447** [comment]
@v4u6h4n 

I think the main problem was that I didn't separate the pages of the different decks. Please remove any pages starting with `ui_` before trying again. The quickest way to do that is by manually deleting the corresponding files in `.var/app/com.core447.StreamController/data/pages/`. Please also make sure that all your decks are connected during the import.

**Comment by merlinlcb** [comment]
Hi Everyone, i was trying out this feature and i do have several issues to report:
every single page on my configs has a change page function returning it back to my main page, the import function is properly recognizing that that is what i want to happen, however the buttons themselves are not carrying over the existing page change(the change page action is there but it is blank), my pages all were attached to custom scripts in ~/bin which (we've already discussed i should and am now intending to use full path to activate them) but they are being turned into Write Text that is just taking in the label and the commands themselves are gone, in places where i had text labels in stream deck linux gui its occasionally adding the text label, adding a write text which uses the label, my main ui is a page of change page functions which are all blank
[ui_AL26J2C07843_1.json](https://github.com/StreamController/StreamController/files/15014291/ui_AL26J2C07843_1.json)
[logs.log](https://github.com/StreamController/StreamController/files/15014296/logs.log)

**Comment by Core447** [comment]
Just to make sure, are you at the head of the `main` branch? Edit: If not you can find the instructions for the source version [here](https://streamcontroller.github.io/docs/latest/installation/#github)

I fixed the problem with the Write Text action.

**Comment by merlinlcb** [comment]
![image](https://github.com/StreamController/StreamController/assets/5841146/a6da2f21-f65c-4c48-8107-a36d11e31018)
i am on the main branch and a git pull did not find any updates

**Comment by Core447** [comment]
> i am on the main branch and a git pull did not find any updates

Are you on commit a873f090f59dcb1c4d52f1278ac2b5aecf41ac44?

**Comment by merlinlcb** [comment]
yes, sorry hadnt attached the screenshot i thought i had

**Comment by Core447** [comment]
Ok, then the problem with the write actions should be solved

**Comment by merlinlcb** [comment]
![image](https://github.com/StreamController/StreamController/assets/5841146/fe9f5357-e495-4c90-8a92-95463226482a)
~~i made sure to delete the pages imported through the ui this time and then confirm they were gone in the folder, incase i missed something last time, that write text is actually what i had for a label on streamdeck linux gui~~ disregard, i somehow had an old copy of the software running change page function commentary is still an issue though..

**Comment by merlinlcb** [comment]
theres also another weird bug occuring, where if you change pages from a page that was generated to a page that was imported, if the page that was imported had keys without set functions and the background is not the default streamdeck background, it will show the generated pages background on the keys that had no set functions, like the imported pages are missing those buttons, adding any label, action, or icon fixes the issue

**Comment by v4u6h4n** [comment]
Alright I had another try, my daily morning routine now lol 

You definitely fixed something, as all pages from all decks are being imported now. Images and backgrounds are fixed (tested my other export that still has images as well to confirm that), then used the previous export that I provided you and am still not having page switching working when the button is pressed. Damn we must be getting close.

[logs.log](https://github.com/StreamController/StreamController/files/15018281/logs.log)

[ui_BL19K1B01105_1.json](https://github.com/StreamController/StreamController/files/15018282/ui_BL19K1B01105_1.json)

https://github.com/StreamController/StreamController/assets/156973064/671bae94-e698-4e27-a4bb-bc795fe61a6c

**Comment by Core447** [comment]
The errors in the video look more like a general problem with page switching rather than one related to the imports. Can you switch between non-imported pages?

I have no problem switching between the imported pages:

https://github.com/StreamController/StreamController/assets/100139110/de602ff2-3a17-456e-b6f1-c1b8f2a5addf

Edit: 679a04995223716380ba5d53f5aac729b34601de might fix the page switching problem

I have a really hard time fixing this because I can't replicate it

**Comment by v4u6h4n** [comment]
I stumbled across a random bug relating to fonts. I haven't deliberately set any fonts, so it must be an accidentally assigned font associated with an empty string? Here is the section of the export with the font:

[logs.log](https://github.com/StreamController/StreamController/files/15031214/logs.log)

```
                "237": {
                    "0": {
                        "state": 0,
                        "states": {
                            "0": {
                                "text": "",
                                "icon": "/media/storage/Streaming/image.svg",
                                "keys": "",
                                "write": "",
                                "command": "\"/media/storage/Streaming/script.sh",
                                "brightness_change": 0,
                                "switch_page": 213,
                                "switch_state": 0,
                                "text_vertical_align": "",
                                "text_horizontal_align": "",
                                "font": "/usr/share/fonts/TTF/VictorMonoNerdFontPropo-ThinOblique.ttf",
                                "font_color": "",
                                "font_size": 0,
                                "background_color": "#ff2020"
                            }
                        }
                    },
```

**Comment by v4u6h4n** [comment]
Okay, another attempt. Same problem. If I click on the page action for one of the buttons, the drop down for the page is empty, even though it is defined in the pages JSON. If I manually configure the page then it works. I inspected the pages JSON and it appears that it may be related to the relative file paths? This is the code for the page that I manually set the JSON path to:

```
"0x0": {
    "labels": {
        "bottom": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font_size": 15,
            "font_family": "",
            "font-family": "",
            "font-size": 15
        },
        "top": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font-family": "",
            "font-size": 15
        },
        "center": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font-family": "",
            "font-size": 15
        }
    },
    "background": {
        "color": [
            255,
            98,
            182,
            255
        ]
    },
    "media": {},
    "actions": [
        {
            "id": "com_core447_DeckPlugin::ChangePage",
            "settings": {
                "selected_page": "/home/user/.var/app/com.core447.StreamController/data/pages/ui_BL25K1B02780_2.json",
                "deck_number": null
            }
        }
    ]
},
```

And this is the path for one which has been automatically assigned a path by the import process:

```
"1x0": {
    "labels": {
        "bottom": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font_size": 15,
            "font_family": "",
            "font-family": "",
            "font-size": 15
        },
        "top": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font-family": "",
            "font-size": 15
        },
        "center": {
            "text": "",
            "color": [
                255,
                255,
                255,
                255
            ],
            "font-family": "",
            "font-size": 15
        }
    },
    "background": {
        "color": [
            255,
            98,
            182,
            255
        ]
    },
    "media": {},
    "actions": [
        {
            "id": "com_core447_DeckPlugin::ChangePage",
            "settings": {
                "selected_page": "data/pages/ui_BL25K1B02780_149.json",
                "deck_number": null
            }
        }
    ]
},
```

When I press the buttons with the latter paths the displays get glitchy.


https://github.com/StreamController/StreamController/assets/156973064/a4559139-1432-429a-91ba-bd51c2418ae7

**Comment by Core447** [comment]
@v4u6h4n 
I think I finally fixed the page importing problem.

> I inspected the pages JSON and it appears that it may be related to the relative file paths?

Yes, this was the issue, I didn't add the config path as a prefix to the page paths. Thank you for noticing this!

**Comment by Core447** [comment]
> theres also another weird bug occuring, where if you change pages from a page that was generated to a page that was imported, if the page that was imported had keys without set functions and the background is not the default streamdeck background, it will show the generated pages background on the keys that had no set functions, like the imported pages are missing those buttons, adding any label, action, or icon fixes the issue

Are you still encountering that problem? If yes, could you please attach a video showing it?

**Comment by v4u6h4n** [comment]
@Core447 

Hells yeah! It works :-) Thanks for all the work getting it fixed.

I'm still playing around with it, for the first time really as I was holding off until we got the import working, but I think perhaps one tweak for the import process that might be worth considering is to prioritise page actions, specifically page changes, above other actions. Some actions, at least when it comes to executing scripts, results in a delay before the page switch action is executed, which disrupts being able to immediately execute additional button presses for subsequent actions if desired, and I can't see much of a benefit to it defaulting to the page action being prioritised lower. The current import method means I'll have to manually re-prioritise the page change actions for every button.

**Comment by Core447** [comment]
@v4u6h4n 
Nice!
I moved the page switch actions to the top

**Comment by v4u6h4n** [comment]
Thanks!

**Comment by v4u6h4n** [comment]
Custom colours from import don't get added to custom colour palette until manually selected.

EDIT: Seems like custom colours reset between sessions, would be nice to have persistence for custom colours.

**Comment by Core447** [comment]
I think it's possible to add them to the custom palette, but I don't know about the restoring. As far as I know GTK itself should take care of that, but maybe it's not always working

**Comment by v4u6h4n** [comment]
They seem to get lost between sessions, but its not a big deal ;-)
